USE studentservices;
Insert into selectieopleiding (Locatie,Naamopleiding,SchoolID,Voltijd_deeltijd) values('Breda','Accountancy',1,1),
('Breda','Accountancy',1,1),
('Breda','Accountancy',1,3),
('Breda','Accountancy Associate degree',1,2),
('Breda','Bedrijfskunde',1,2),
('Breda','Bedrijfskunde',1,1),
('Breda','Bedrijfskunde Associate degree',1,2),
('Breda','Business IT & Management',1,2),
('Breda','Business IT & Management',1,1),
('Breda','Commerciële Economie',1,2),
('Breda','Commerciële Economie',1,1),
('Breda','Communicatie',1,2),
('Breda','Communicatie',1,1),
('Breda','Communicatie Associate degree',1,2),
('Breda','Finance & Control',1,2),
('Breda','Finance & Control',1,1),
('Breda','Finance & Control (international)',1,1),
('Breda','Human Resource Management',1,2),
('Breda','Human Resource Management',1,1),
('Breda','Human Resource Management Associate degree',1,2),
('Breda','Industrial Engineering & Management',1,1),
('Breda','Informatica',1,2),
('Breda','Informatica',1,1),
('Breda','Integrale Veiligheidskunde',1,1),
('Breda','International Business',1,1),
('Breda','Management in de Zorg',1,2),
('Breda','Management in de Zorg Associate degree',1,2),
('Breda','Marketing Management Associate degree',1,2),
('Breda','Ondernemerschap & Retail Management',1,2),
('Breda','Ondernemerschap & Retail Management',1,1),
('Breda','Ondernemerschap & Retail Management Associate degree',1,2);

Insert into selectieopleiding (Locatie,Naamopleiding,SchoolID,Voltijd_deeltijd)  values('Breda','Accountancy',17,1),
('Rotterdam','Accountancy',17,1),
('Rotterdam','Aeronautical Engineering (EN)',17,1),
('Rotterdam','Associate degree Business Studies Logistiek',17,1), 
('Rotterdam','Associate degree Crossmediale Communicatie',17,1), 
('Rotterdam','Associate degree Facilitair Eventmanagement',17,1),
('Rotterdam','Associate degree Finance & Control (Ad Bedrijfseconomie)',17,1),
('Rotterdam','Associate degree IT Service Management',17,1), 
('Ro0tterdam','Associate degree IT Service Management',17,2),
('Rotterdam','Associate degree Pedagogisch Educatief Professional',17,2),
('Rotterdam','Associate degree Sociaal Financiële Dienstverlening',17,2),
('Rotterdam','Associate degree Tuinbouwmanagement',17,1),
('Rotterdam','Biologie en Medisch Laboratoriumonderzoek',17,1),
('Rotterdam','Biotechnologie',17,1), 
('Rotterdam','Bouwkunde',17,1), 
('Rotterdam','Bouwmanagement & Vastgoed / Ruimtelijke Ontwikkeling',17,1), 
('Rotterdam','Business Innovation (EN)',17,1), 
('Rotterdam','Business IT & Management',17,1), 
('Rotterdam','Business IT & Management',17,2), 
('Rotterdam','Business Studies',17,1), 
('Rotterdam','Chemie',17,1), 
('Rotterdam','Civiele Techniek',17,1), 
('Rotterdam','Communicatie',17,1), 
('Rotterdam','Creative Business',17,1), 
('Rotterdam','Creative Business (EN)',17,1), 
('Rotterdam','Dier- en Veehouderij',17,1), 
('Rotterdam','Elektrotechniek',17,1), 
('Rotterdam','Elektrotechniek',17,2), 
('Rotterdam','Facility Management',17,1),
('Rotterdam','Finance & Control: Bedrijfseconomie',17,1), 
('Rotterdam','Food Commerce and Technology',17,1), 
('Rotterdam','HBO - Rechten',17,1), 
('Rotterdam','HBO - Rechten',17,2), 
('Rotterdam','Informatica',17,1), 
('Rotterdam','Information Technology (EN)',17,1),
('Rotterdam','Integrale Veiligheidskunde',17,1), 
('Rotterdam','Integrale Veiligheidskunde',17,2), 
('Rotterdam','Landscape and Environment Management',17,1), 
('Rotterdam','Leisure & Events Management',17,1), 
('Rotterdam','Leraar Basisonderwijs (Pabo)',17,1), 
('Rotterdam','Leraar Basisonderwijs (Pabo)',17,3), 
('Rotterdam','Leraar Basisonderwijs (Pabo)',17,2), 
('Rotterdam','Leraar Basisonderwijs Digitaal (DigiPabo)',17,2), 
('Rotterdam','Luchtvaarttechnologie',17,1), 
('Rotterdam','Master Advanced Health Informatics Practice',17,2), 
('Rotterdam','Master Educational Leadership',17,2), 
('Rotterdam','Master Leren en Innoveren',17,2), 
('Rotterdam','Master Medical Imaging / Radiation Oncology',17,2), 
('Rotterdam','Master of Advanced Nursing Practice',17,4), 
('Rotterdam','Master Pedagogiek',17,2), 
('Rotterdam','Master Physician Assistant',17,4), 
('Rotterdam','Mathematical Engineering (EN)',17,1), 
('Rotterdam','Medisch Beeldvormende en Radiotherapeutische Technieken',17,1), 
('Rotterdam','Medisch Beeldvormende en Radiotherapeutische Technieken',17,4), 
('Rotterdam','Mondzorgkunde',17,1),
('Rotterdam','Muziek',17,1), 
('Rotterdam','Pedagogiek',17,1), 
('Rotterdam','Precision Engineering (afstudeerrichting Luchtvaarttechnologie)',17,1), 
('Rotterdam','Sociaal Juridische Dienstverlening',17,1), 
('Rotterdam','Sociaal Juridische Dienstverlening',17,2), 
('Rotterdam','Social Work',17,1), 
('Rotterdam','Social Work',17,2), 
('Rotterdam','Sportkunde',17,1), 
('Rotterdam','Technische Bedrijfskunde',17,1), 
('Rotterdam','Technische Bedrijfskunde',17,2), 
('Rotterdam','Technische Informatica',17,1), 
('Rotterdam','Tourism Management',17,1), 
('Rotterdam','Tourism Management (EN)',17,1), 
('Rotterdam','Tuinbouw & Agribusiness',17,1), 
('Rotterdam','Tuinbouw & Agribusiness',17,2), 
('Rotterdam','Verloskunde',17,1), 
('Rotterdam','Verpleegkunde',17,1), 
('Rotterdam','Verpleegkunde',17,4), 
('Rotterdam','Verpleegkunde',17,2), 
('Rotterdam','Werktuigbouwkunde',17,1), 
('Rotterdam','Werktuigbouwkunde',17,2)