INSERT INTO SCHOOL ('Avans Hogeschool'),
('Aeres Hogeschool'),
('Amsterdamse Hogeschool voor de Kunsten'),
('ArtEZ Hogeschool voor de Kunsten'),
('Breda University of Applied Sciences'),
('Christelijke Hogeschool Ede'),
('Codarts Rotterdam'),
('De Haagse Hogeschool'),
('Design Academy Eindhoven'),
('Driestar hogeschool'),
('Fontys Hogescholen'),
('Gerrit Rietveld Academie'),
('Hanzehogeschool Groningen'),
('HAS Hogeschool'),
('Hogeschool de Kempel'),
('Hogeschool der Kunsten Den Haag'),
('Hogeschool Inholland'),
('Hogeschool iPabo'),
('Hogeschool Leiden'),
('Hogeschool Rotterdam'),
('Hogeschool Utrecht'),
('Hogeschool van Amsterdam'),
('Hogeschool van Arnhem en Nijmegen'),
('Hogeschool Viaa'),
('Hogeschool voor de Kunsten Utrecht'),
('Hotelschool The Hague'),
('HZ University of Applied Sciences'),
('Iselinge Hogeschool'),
('Katholieke Pabo Zwolle'),
('Marnix Academie'),
('NHL Stenden Hogeschool'),
('Saxion'),
('Thomas More Hogeschool'),
('Van Hall Larenstein University of Applied Sciences'),
('Windesheim'),
('Zuyd Hogeschool')